### ISSUE TITLE
TestRuns fails 'Persistor not set'

### ISSUE THREAD

**Issue by stijngoedertier** [interactive-instruments/etf-webapp-docker#7]
Hi Jon and Clemens, I wanted to give the ETF-webapp a try to validate a GML dataset. I managed to get the Docker image running on my local Docker host and I can configure a TestRun and upload a GML file. However, when I want to start the TestRun, I get error 500 '**Persistor not set**'. Does this ring a bell to you? Thanks in advance for your help with this.

In the log file [etf.log.txt](https://github.com/interactive-instruments/etf-webapp-docker/files/1077200/etf.log.txt) , I find the following:

2017-06-15 09:11:23.574 [qtp1973538135-17] ERROR d.i.e.w.c.RestExceptionHandler - EXID-1497517883574: An exception occurred while trying to invoke "http://192.168.99.100:8082/etf-webapp/v2/TestRuns"
java.lang.IllegalStateException: Failed to invoke handler method
HandlerMethod details: 
Controller [de.interactive_instruments.etf.webapp.controller.TestRunController]
Method [public void de.interactive_instruments.etf.webapp.controller.TestRunController.start(de.interactive_instruments.etf.webapp.dto.StartTestRunRequest,org.springframework.validation.BindingResult,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws de.interactive_instruments.etf.webapp.controller.LocalizableApiError]
Resolved arguments: 
[0] [type=de.interactive_instruments.etf.webapp.dto.StartTestRunRequest] [value=de.interactive_instruments.etf.webapp.dto.StartTestRunRequest@a14118c]
[1] [type=org.springframework.validation.BeanPropertyBindingResult] [value=org.springframework.validation.BeanPropertyBindingResult: 0 errors]
[2] [type=org.eclipse.jetty.server.Request] [value=Request(POST //192.168.99.100:8082/etf-webapp/v2/TestRuns)@202db34]
[3] [type=org.eclipse.jetty.server.Response] [value=HTTP/1.1 200 
Access-Control-Allow-Origin: http://192.168.99.100:8082/etf-webapp

]
```

	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:226)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: de.interactive_instruments.etf.webapp.controller.LocalizableApiError: java.lang.NullPointerException: Persistor not set
	at de.interactive_instruments.etf.webapp.controller.TestRunController.initAndSubmit(TestRunController.java:244)
	at de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:507)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	... 42 common frames omitted
Caused by: java.lang.NullPointerException: **Persistor not set**
	at java.util.Objects.requireNonNull(Objects.java:228)
	at de.interactive_instruments.etf.testdriver.AbstractTestTask.getPersistor(AbstractTestTask.java:157)
	at de.interactive_instruments.etf.testdriver.bsx.BasexTestTask.<init>(BasexTestTask.java:114)
	at de.interactive_instruments.etf.testdriver.bsx.BsxTestDriver.createTestTask(BsxTestDriver.java:112)
	at de.interactive_instruments.etf.testdriver.DefaultTestDriverManager.createTestRun(DefaultTestDriverManager.java:207)
	at de.interactive_instruments.etf.testdriver.TestDriverManager.createTestRun(TestDriverManager.java:53)
	at de.interactive_instruments.etf.webapp.controller.TestDriverController.create(TestDriverController.java:147)
	at de.interactive_instruments.etf.webapp.controller.TestRunController.initAndSubmit(TestRunController.java:226)
	... 48 common frames omitted


```

**Comment by cportele** [comment]
Thanks, Stijn. Jon is already looking at the issue. Stay tuned...

**Comment by jonherrmann** [comment]
Fixed. Thanks Stijn, please [update](https://github.com/interactive-instruments/etf-webapp-docker#update-etf) your local docker instance.

**Comment by stijngoedertier** [comment]
Thank you, Jon and Clemens for your quick response. This is indeed fixed. I now managed to execute a testrun.  This is going to be very useful!

I noticed that it may take a while for the updates to the Docker image / etf war file to take effect. When I updated my Docker image yesterday afternoon, at first nothing was changed and the problem remained (build number etf WebApp 2.0.0-b170612T1825). After retrying that today the build number changed into etf WebApp 2.0.0-b170607T1123 and it worked.

**Comment by jonherrmann** [comment]
Thanks for the feedback.

The webapp itself was not updated (latest version is still b170612...), but only the BaseX test driver.

I can't retrace why this webapp version was delivered to you. I now changed a setting in our repository and I would like to ask you to update your instance again, to check if this fixes the version issue.

**Comment by stijngoedertier** [comment]
Thank you, Jon. I am on b170612T1825 today (yesterday's docker-compose build on b170607). I mixed the numbers up in my earlier post. :-)

Anyway, glad that this is working now.
